### ISSUE TITLE
Integration with Redis PubSub

### ISSUE THREAD

**Issue by sidutta** [edvinerikson/relay-subscriptions#28]
Is there an example that demonstrates usage of this package in environments that require high scalability?

**Comment by edvinerikson** [comment]
This library is the client implementation of the subscriptions model and does not have anything to do with the backend implementation. Not sure how to best answer your question because the library itself works with any backend implementation. If your backend scales well I cannot answer.


Going to close the issue but if you feel that your question hasn't been answered feel free to re-open. :)
