### ISSUE TITLE
Support Relay 1.3.0

### ISSUE THREAD

**Issue by maikelrobier** [edvinerikson/relay-subscriptions#38]
Hi, I tried upgrading to `react-relay` 1.3.0 and I get this error on runtime:

![image](https://user-images.githubusercontent.com/16763041/30343403-14f8f054-97c3-11e7-9870-d27fec64041e.png)

I guess that's probably caused by the refactoring done in [version 1.3.0](https://github.com/facebook/relay/releases/tag/v1.3.0) to replace promises by observables.

Is this something that has to be updated in `relay-subscriptions` or is it just something that I got wrong? Thanks.

**Comment by ronal2do** [comment]
+ 1

**Comment by taion** [comment]
The example uses 1.4.1 and it works just fine: https://github.com/edvinerikson/relay-subscriptions/blob/master/examples/todo/package.json#L25

**Comment by sibelius** [comment]
I think this is a problem on graphql implementation, not with this package

**Comment by stefanfoulis** [comment]
@taion Does that mean that relay-subscriptions works with relay "modern". I'm getting confused because the README explicitly mentions "Relay Classic":
<img width="346" alt="screen shot 2018-01-31 at 22 37 21" src="https://user-images.githubusercontent.com/14330/35648850-6510de02-06d7-11e8-8b72-97ec74c3251d.png">

**Comment by taion** [comment]
It works with Relay Classic running on Relay v1.

**Comment by stefanfoulis** [comment]
@taion thanks for the clarification 👍
